name: FinSetsForCAP
version: "2020.04.01"
license: "GPL-2.0-or-later"
date: 2020-04-01
description: |
    The elementary topos of (skeletal) finite sets

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Julia Mickisch
      url: https://github.com/juliamick/
    - name: Fabian Zickgraf
      url: https://github.com/zickgraf/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2019.12.12"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "Toposes"
      version: ">= 2019.11.15"
      url: "https://homalg-project.github.io/Toposes"

www: https://github.com/homalg-project/FinSetsForCAP
readme: README.md
packageinfo: https://raw.githubusercontent.com/homalg-project/FinSetsForCAP/master/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/FinSetsForCAP/releases/download/v2020.04.01/FinSetsForCAP-2020.04.01.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BMZ20</span>]   <b class='BibAuthor'>Barakat, M., Mickisch, J. and Zickgraf, F.</b>,
     <i class='BibTitle'>FinSetsForCAP, The elementary topos of (skeletal) finite sets,
             Version 2020.04.01</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/homalg-project/FinSetsForCAP">https://github.com/homalg-project/FinSetsForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ FinSetsForCAP2020.04.01,
      author =           {Barakat, M. and Mickisch, J. and Zickgraf, F.},
      title =            {{FinSetsForCAP}, The elementary topos of (skeletal) finite sets, {V}ersion 2020.04.01},
      month =            {Apr},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href    {https://github.com/homalg-project/FinSetsForCAP}    {\texttt{https://github.com/}\discretionary   {}{}{}\texttt{homalg-project/}\discretionary
                          {}{}{}\texttt{FinSetsForCAP}}},
      printedkey =       {BMZ20}
    }

