version: 2.1
jobs:
  test:
    parameters:
      docker_image:
        type: string
    docker:
      - image: << parameters.docker_image >>:latest
    working_directory: ~/.gap/pkg/FinSetsForCAP
    steps:
      - checkout
      - run: |
          sudo apt -o Acquire::https::Verify-Peer="false" update
          sudo apt -o Acquire::https::Verify-Peer="false" dist-upgrade -y
          sudo apt -o Acquire::https::Verify-Peer="false" install -y texlive-latex-extra texlive-science curl
          cd ..
          git clone --depth 1 https://github.com/gap-packages/AutoDoc.git
          git clone --depth 1 https://github.com/homalg-project/homalg_project.git
          git clone --depth 1 https://github.com/homalg-project/CAP_project.git
          git clone --depth 1 https://github.com/homalg-project/Toposes.git
          cd FinSetsForCAP
          TERM=dumb make ci-test
workflows:
  version: 2
  commit:
    jobs:
      - test:
          docker_image: gapsystem/gap-docker
          filters:
            branches:
              only:
                - master
                - /.*-ci/
  nightly:
    triggers:
      - schedule:
          # 0:00 UTC = 1:00 CET = 2:00 CEST
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test:
          docker_image: gapsystem/gap-docker-master
